import random # import a module named ramdom (pre built in)

# random.randrange(-1, 10) 
# use the randrange function from the random module to generate a random number
#between -1 and 10 (not including 10)

# * r = random.randrange(-1, 10) # use the randrange function from the random module 
# to generate a random number
# between -1 and 10 (not including 10)

# print (r) # print the random number generated by the randrange function

# OR you can also use the randint function from the random module 
# to generate a random number and a alphabet
# * r = random.randint(-1, 10) # use the randint function
# from the random module to generate a random number 
# between the given/defined range (including 10)

# OR you can also type above code as 
# * r = random.randint (11)
# the above code will generate a random number between 0 and 10 (including 10)
# because the default starting point is 0

# print(r) # print the random number generated by the randint function

# *random_number = random.randint(100) # use the randint function from the random module 
# to generate a random number
# between 1 and 100 (including 100)

top_of_range = input("Type a number: ") # top_of_range is the variable that stores the user input
# the user is prompted to type a number and the input is stored in the variable top_of

if top_of_range.isdigit(): # if statement is used to check if the user input is a digit
    top_of_range = int(top_of_range) # if the user input is a digit, it is converted to an integer
    if top_of_range <= 0: # if statement is used to check if the user input is less than or equal to 0
        print("Please type a number larger than 0 next time.") # if the user input is less than or equal to 0, it will print this message
        quit() # quit() is a built-in function that exits the program

else: # else statement is used to execute a block of code if the condition in the if statement is false
    print("Please type a number next time.") # if the user input is not a digit, it will print this message
    quit() # quit() is a built-in function that exits the program

random_number = random.randint(0, top_of_range) # use the randint function from the random module to generate a random number
# between 0 and the user input (including the user input)

guesses = 0 # guesses is the variable that stores the number of guesses the user has made and is initialized to 0

print(random_number) # print the random number generated by the randint function    

while True: # while the top line is TRUE
    # while loop is used to execute a block of code repeatedly as long as the condition is true
    
    guesses += 1 # increment the guesses variable by 1

    user_guess = input("Make a guess: ") # user_guess is the variable that stores the user input
    # the user is prompted to make a guess and the input is stored in the variable user_guess

    if user_guess.isdigit(): # if statement is used to check if the user input is a digit
        user_guess = int(user_guess) # if the user input is a digit, it is converted to an integer
    else: # else statement is used to execute a block of code if the condition in the if statement is false
        print("Please type a number next time.") # if the user input is not a digit, it will print this message
        continue # brings us back to the top of the loop; 
        # continue is a built-in function that skips the rest of the code inside the loop for the current iteration and moves to the next iteration
        # break is the opposite of continue; it exits the loop when called  

    if user_guess == random_number: # if statement is used to check if the user input is equal to the random number generated by the randint function
        print("You got it!") # if the user input is correct, it will print "You got it!"
        break # break is a built-in function that exits the loop when called

    elif user_guess > random_number: # elif statement is used to check if the user input is greater than the random number generated by the randint function
        print("You were above the number!") # if the user input is greater than the random number, it will print this message
        #can have as many elif statements as you want
        
    else: # else statement is used to execute a block of code if none of the conditions in the previous statements are true
        print("You were below the number!") # if the user input is less than the random number, it will print this message

print("You got it in", guesses, "guesses") # print the number of guesses the user has made to get the correct answer    
# or you can also type above code as
# print("You got it in " + str(guesses) + " guesses") # print the number of guesses the user has made to get the correct answer


